;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	))

(setq mc/cmds-to-run-once
      '(
	darp--add-bottom-cursor-or-remove-from-top
	darp--add-top-cursor-or-remove-from-bottom
	mc/mark-next-lines
	mc/mark-previous-lines
	))
